services:
  app:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8002:8001"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - backend

  db:
    image: postgres:13
    container_name: fastapi-db
    restart: always
    environment:
      - POSTGRES_USER=user_observ
      - POSTGRES_PASSWORD=pass_observ
      - POSTGRES_DB=empresa_pia
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: fastapi-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
