"""Tables Sidra

Revision ID: 27309cbead6f
Revises: 6f6190a4cbcc
Create Date: 2025-03-23 16:07:15.705590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27309cbead6f'
down_revision: Union[str, None] = '6f6190a4cbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade_economica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_cnae', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atividade_economica_codigo_cnae'), 'atividade_economica', ['codigo_cnae'], unique=True)
    op.create_index(op.f('ix_atividade_economica_descricao'), 'atividade_economica', ['descricao'], unique=True)
    op.create_index(op.f('ix_atividade_economica_id'), 'atividade_economica', ['id'], unique=False)
    op.create_table('componente_transformacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_componente_transformacao_id'), 'componente_transformacao', ['id'], unique=False)
    op.create_index(op.f('ix_componente_transformacao_nome'), 'componente_transformacao', ['nome'], unique=True)
    op.create_table('periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodo_ano'), 'periodo', ['ano'], unique=True)
    op.create_index(op.f('ix_periodo_id'), 'periodo', ['id'], unique=False)
    op.create_table('dados_transformacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atividade_economica_id', sa.Integer(), nullable=False),
    sa.Column('componente_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['atividade_economica_id'], ['atividade_economica.id'], ),
    sa.ForeignKeyConstraint(['componente_id'], ['componente_transformacao.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dados_transformacao_id'), 'dados_transformacao', ['id'], unique=False)
    op.create_index(op.f('ix_dados_transformacao_valor'), 'dados_transformacao', ['valor'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dados_transformacao_valor'), table_name='dados_transformacao')
    op.drop_index(op.f('ix_dados_transformacao_id'), table_name='dados_transformacao')
    op.drop_table('dados_transformacao')
    op.drop_index(op.f('ix_periodo_id'), table_name='periodo')
    op.drop_index(op.f('ix_periodo_ano'), table_name='periodo')
    op.drop_table('periodo')
    op.drop_index(op.f('ix_componente_transformacao_nome'), table_name='componente_transformacao')
    op.drop_index(op.f('ix_componente_transformacao_id'), table_name='componente_transformacao')
    op.drop_table('componente_transformacao')
    op.drop_index(op.f('ix_atividade_economica_id'), table_name='atividade_economica')
    op.drop_index(op.f('ix_atividade_economica_descricao'), table_name='atividade_economica')
    op.drop_index(op.f('ix_atividade_economica_codigo_cnae'), table_name='atividade_economica')
    op.drop_table('atividade_economica')
    # ### end Alembic commands ###
