"""Adicionar índices compostos em dados_transformacao

Revision ID: de9eccef5f0f
Revises: edc074c184d0
Create Date: 2025-03-23 17:55:31.242866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9eccef5f0f'
down_revision: Union[str, None] = 'edc074c184d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dados_transformacao_atividade_componente_periodo', 'dados_transformacao', ['atividade_economica_id', 'componente_id', 'periodo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dados_transformacao_atividade_componente_periodo', table_name='dados_transformacao')
    # ### end Alembic commands ###
