"""Corrigindo relacionamento

Revision ID: edc074c184d0
Revises: 27309cbead6f
Create Date: 2025-03-23 16:37:19.908201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc074c184d0'
down_revision: Union[str, None] = '27309cbead6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dados_transformacao_valor', table_name='dados_transformacao')
    op.create_index(op.f('ix_dados_transformacao_valor'), 'dados_transformacao', ['valor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dados_transformacao_valor'), table_name='dados_transformacao')
    op.create_index('ix_dados_transformacao_valor', 'dados_transformacao', ['valor'], unique=True)
    # ### end Alembic commands ###
